#!/bin/bash
# Setup Ollama on RHEL8 with ALL data in /moneyball

echo "=== Setting up Ollama on RHEL8 (using /moneyball) ==="

# Set Ollama to use /moneyball for data
export OLLAMA_MODELS="/moneyball/ollama/models"
export OLLAMA_HOME="/moneyball/ollama"

echo "Setting Ollama directories:"
echo "OLLAMA_HOME=$OLLAMA_HOME"
echo "OLLAMA_MODELS=$OLLAMA_MODELS"

# Create directories
mkdir -p "$OLLAMA_HOME"
mkdir -p "$OLLAMA_MODELS"

# Add to bashrc for persistence
echo "" >> ~/.bashrc
echo "# Ollama paths" >> ~/.bashrc
echo "export OLLAMA_HOME=/moneyball/ollama" >> ~/.bashrc
echo "export OLLAMA_MODELS=/moneyball/ollama/models" >> ~/.bashrc

# Install Ollama
echo ""
echo "Installing Ollama..."
curl -fsSL https://ollama.ai/install.sh | sh

# Check if installed
if command -v ollama &> /dev/null; then
    echo "✓ Ollama installed successfully"
    ollama --version
else
    echo "✗ Ollama installation failed"
    exit 1
fi

# Start Ollama service with /moneyball paths
echo ""
echo "Starting Ollama service..."
OLLAMA_HOME="$OLLAMA_HOME" OLLAMA_MODELS="$OLLAMA_MODELS" ollama serve > /moneyball/ollama/ollama.log 2>&1 &
OLLAMA_PID=$!
sleep 5

# Create working directory
cd /moneyball/whisper-rtx-deployment

# Create Modelfile for your Gemma GGUF
MODEL_PATH="/moneyball/whisper-rtx-deployment/models/gemma-2-9b-it-Q5_K_M.gguf"

echo ""
echo "Creating Modelfile for Gemma..."
cat > /moneyball/ollama/Modelfile << EOF
FROM $MODEL_PATH

PARAMETER temperature 0.7
PARAMETER top_p 0.9
PARAMETER num_ctx 2048
EOF

# Create the model in Ollama
echo ""
echo "Creating Gemma model in Ollama..."
ollama create gemma2-legal -f /moneyball/ollama/Modelfile

# Test the model
echo ""
echo "Testing Gemma model..."
ollama run gemma2-legal "Summarize: Customer called about loan status."

# Create legal summary script in /moneyball
cat > /moneyball/whisper-rtx-deployment/gemma_legal_summary_ollama.py << 'PYTHON_EOF'
#!/usr/bin/env python3
"""
Legal summary generator using Ollama Gemma
All data stored in /moneyball
"""
import subprocess
import os
from pathlib import Path

# Ensure Ollama uses /moneyball
os.environ['OLLAMA_HOME'] = '/moneyball/ollama'
os.environ['OLLAMA_MODELS'] = '/moneyball/ollama/models'

def query_gemma_ollama(prompt):
    """Query Gemma using Ollama CLI"""
    cmd = ["ollama", "run", "gemma2-legal"]
    
    full_prompt = f"""You are a legal assistant. Create a professional legal summary.
{prompt}

Legal Summary:"""
    
    try:
        result = subprocess.run(
            cmd,
            input=full_prompt,
            capture_output=True,
            text=True
        )
        if result.returncode == 0:
            return result.stdout.strip()
        else:
            return f"Error: {result.stderr}"
    except Exception as e:
        return f"Error: {e}"

def process_transcript(transcript_file):
    """Process a transcript file and generate legal summary"""
    transcript = Path(transcript_file).read_text()
    
    # Truncate if too long
    if len(transcript) > 2000:
        transcript = transcript[:2000] + "..."
    
    prompt = f"Summarize this call transcript:\n{transcript}"
    
    summary = query_gemma_ollama(prompt)
    
    # Save summary in /moneyball
    output_file = Path(transcript_file).with_suffix('.legal_summary.txt')
    output_file.write_text(f"Legal Summary (Generated by Gemma 2 9B)\n{'='*50}\n{summary}")
    
    print(f"Summary saved to: {output_file}")
    return summary

if __name__ == "__main__":
    # Test with Eric Rawlins transcript
    test_transcript = "Eric Rawlins called about loan modification status. Application submitted June 1st."
    print("Test summary:", query_gemma_ollama(f"Summarize: {test_transcript}"))
PYTHON_EOF

chmod +x /moneyball/whisper-rtx-deployment/gemma_legal_summary_ollama.py

echo ""
echo "=== Setup Complete ==="
echo "Everything is stored in /moneyball:"
echo "- Ollama home: /moneyball/ollama"
echo "- Models: /moneyball/ollama/models"
echo "- Logs: /moneyball/ollama/ollama.log"
echo "- Scripts: /moneyball/whisper-rtx-deployment/"
echo ""
echo "To use:"
echo "1. Quick test: ollama run gemma2-legal 'Summarize: Customer called about loan'"
echo "2. Python script: /moneyball/whisper-rtx-deployment/gemma_legal_summary_ollama.py"
echo "3. Stop Ollama: kill $OLLAMA_PID"